####################################################
# RULE for CICS Agent Outbound to RTCP
####################################################
TTLSConfig /etc/pagent/pagent_TTLS.conf

####################################################
# FINAL z/OS 3.1 AT-TLS POLICY (TLS 1.3 ONLY)
####################################################

TTLSGroupAction Group_Action_All
{
  TTLSEnabled On
}

# Correct block for curves and shares in z/OS 3.1
TTLSSignatureParms Signature_Standard
{
  ClientKeyShareGroups  X25519
  ClientKeyShareGroups  SECP256R1
  ClientECurves         X25519
  ClientECurves         SECP256R1

  SignaturePairs        RSA_PKCS1_SHA256
  SignaturePairs        RSA_PSS_RSAE_SHA256
}

TTLSEnvironmentAdvancedParms Env_Adv_Standard
{
  SSLv3                 OFF
  TLSv1                 OFF
  TLSv1.1               OFF
  TLSv1.2               ON
  TLSv1.3               ON

  # SNI for Kubernetes Ingress
  #ClientHandshakeSNI      Optional
  #ClientHandshakeSNIMatch Optional
  #ClientHandshakeSNIList  master-hcl.tp-k8s.nonprod.hclpnp.com
  ClientHandshakeSNI    Off   # Keep this Off to prevent RC 447
  Renegotiation         All   # Keep this for interceptor
}

TTLSCipherParms Ciphers_Standard
{
  V3CipherSuites TLS_AES_256_GCM_SHA384
  V3CipherSuites TLS_AES_128_GCM_SHA256
  V3CipherSuites TLS_CHACHA20_POLY1305_SHA256
  # TLS 1.2 (REQUIRED for most connections)
  V3CipherSuites TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  V3CipherSuites TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  V3CipherSuites TLS_RSA_WITH_AES_256_GCM_SHA384
}

TTLSEnvironmentAction Outbound_Env_Action
{
  HandshakeRole Client
  TTLSKeyringParms
  {
    Keyring RITADM/THRING
  }

  TTLSEnvironmentAdvancedParmsRef Env_Adv_Standard
  TTLSCipherParmsRef Ciphers_Standard
  TTLSSignatureParmsRef Signature_Standard
}

TTLSRule Outbound_RTCP_Rule
{
  RemoteAddr 10.134.59.21
  RemotePortRange 443
  Direction Outbound
  TTLSGroupActionRef Group_Action_All
  TTLSEnvironmentActionRef Outbound_Env_Action
}
