#Silent Installation Configuration File

# Do not change this attribute.
INSTALLER_UI=silent

# The directory where the installer will get installed.
# For Windows, directories should be separated with double backslash. (\\)
# For Ex: 
# C:\\Program Files\\MFTWebservices
USER_INSTALL_DIR=C:\\Program Files\\MFTWebservices

# This attribute decides whether to install both RESTful API Interface and Web Console or only RESTful API Interface.
# Valid Values are:
# 1 -> RESTful API Interface and Web Console
# 2 -> RESTful API Interface
INSTALLATION_TYPE=1

# Do not change this attribute
CHOSEN_INSTALL_SET=Complete

#Port for Web Server
#--------------------
# Jetty server will be deployed on this port.
# Valid values range from 1025-65535
SSL_PORT=9443

#Keystore
#--------
# This password will be used for the ssl-server.jks (key store) database creation, where the key certificates will be placed.
# This can be either clear text or base64 encoded password.
# When clear text password is provided, during the installation the value will be encrypted and written back to this file.
# Password length must be at least 6 characters.
KEYSTORE_PASS=YWJjMTIz

# This should be same as KEYSTORE_PASS
CONFIRM_PASS=YWJjMTIz

#Truststore
#----------
# This password will be used for the trustedkeystore.jks (trust store) database creation, where the trusted certificates will be placed.
# This can be either clear text or base64 encoded password.
# When clear text password is provided, during the installation the value will be encrypted and written back to this file.
# Password length must be at least 6 characters.
TRUSTSTORE_PASS=YWJjMTIz

# This should be same as TRUSTSTORE_PASS
CONFIRM_TRUSTSTORE_PASS=YWJjMTIz

#Certificate
#-----------
# This attribute decides whether to generate the user defined certificate or to add ca signed certificate.
# Valid Values are:
# 1 -> Generate Self Signed certificate
# 2 -> Import CA Signed certificate
CERTIFICATE_TYPE=1

#CA certificate
#-----------------------
# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 2 (i.e. CA Signed certificate).
# This should contain the full path of the file with the file name.
# It only considers PEM or PKCS12 format extension certificate.
# The file must contain the private key, the CA-signed certificate, the CA certificate and all intermediate certificates.
# For Windows, directories should be separated with double backslash. (\\)
# For Ex: C:\\Certificates\\certFile.pem
CA_CERTIFICATE_FILE=

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 2 (i.e. CA Signed certificate).
# This should contain the private key password of the CA Signed Certificate.
# This can be either clear text or base64 encoded password.
# When clear text password is provided, during the installation the value will be encrypted and written back to this file.
CA_CERTIFICATE_PASSWORD=

#Certificate Label
#-----------------
# This would be the certificate label (alias) of the certificate needed for "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate) or 2 (i.e. Import CA Signed certificate).
# This should be entered in small case.
CERTIFICATE_LABEL=mftwebservices

#Self Signed certificate
#-----------------------
# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# This would be the expiry time to be mentioned in day(s). It should be greater than 0.
CERTIFICATE_EXPIRY_TIME=365

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# This would be the Common Name of the certificate.
# Do not use special characters (?, $, % and so on), IP addresses, Port numbers, or "http:// or https://" in the common name.
COMMON_NAME=localhost

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# The Organization Name (corporation, limited partnership, university, or government agency)
# must be registered with some authority at the national, state, or city level. 
# Use the legal name under which your organization is registered.
# Do not abbreviate or use any of these symbols: ! @ # $ % ^ * ( ) ~ ? > < / \.
ORGANISATION=OrganizationName

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# Locality denotes the city in which the organization is located.
LOCALITY=Irving

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# State, in which the organization is located.
STATE=Texas

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# This field contains the 2-character ISO format country code.
COUNTRY=US

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# This should contain the support email ID.
EMAIL_ID=noreply@noreply.com

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# This should contain the DNS name(localhost or system hostname).
DNS_NAME=localhost

# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# This should contain the IP address(127.0.0.1 or system IPv4 address).
IP_ADDR=127.0.0.1

#Export Self Signed Public Certificate
#-------------------------------
# Below property would only be needed if "CERTIFICATE_TYPE" is equal to 1 (i.e. Generate Self Signed certificate).
# This exported public certificate can be imported to truststore of the server to make secure connection.
# The directory where the self-signed public certificate will get exported.
# For Windows, directories should be separated with double backslash. (\\)
# For Ex: C:\\Program Files\\MFTWebservices
# If set empty, then export will be skipped during installation, and you can export certificate later via CDWS Admin UI.
EXPORT_CERTIFICATE_LOC=

#Import Trusted Certificate
#-------------------------------
# Below properties would only be needed to add trusted certificate in truststore of the CDWS to make secure connection with the connect direct node.
# This should contains the full path of the file with the file name.
# It only considers PEM format extension certificate.
# For Windows, directories should be separated with double backslash. (\\)
# For Ex: C:\\Certificates\\trustFile.pem
# If set empty, then import will be skipped during installation, and you can import certificate later into trusted store via CDWS Admin UI.
TRUST_CERTIFICATE_FILE=